@startuml

abstract class World
class MyStage


' Files: Object_Controlers

class ButtonClass



' Files: SceneClasses/gameSceneClasses




' Files: SceneClasses/HighScore/HighScoreControlers


package "Object Controlers" #DDDDDD {
  ' Files: Object_Controlers/InteractiveObjects
  class ImageView
  abstract class Actor

  ' connections
  ImageView <|- Actor
  abstract class World
  class MyStage
}
package "Controllers" #DDDDDD {
class Animal
  class coordinateArea
  class End
  class Log
  class Obstacle
  class PushingWall
  class Turtle
  class wall
  class waterArea
  class WetTurtle
  class BackgroundImage
  class Digit
  Actor <|- Animal
  Actor <|- coordinateArea
  Actor <|- End
  Actor <|- Log
  Actor <|- Obstacle
  Actor <|- PushingWall
  Actor <|- Turtle
  Actor <|- wall
  Actor <|- waterArea
  Actor <|- WetTurtle
  Actor <|- BackgroundImage
  Actor <|- Digit
}
  MyStage "1" *-- "many" Animal
  MyStage "1" *-- "many" coordinateArea
  MyStage "1" *-- "many" End
  MyStage "1" *-- "many" Log
  MyStage "1" *-- "many" Obstacle
  MyStage "1" *-- "many" PushingWall
  MyStage "1" *-- "many" Turtle
  MyStage "1" *-- "many" wall
  MyStage "1" *-- "many" waterArea
  MyStage "1" *-- "many" WetTurtle
  MyStage "1" *-- "many" BackgroundImage
  MyStage "1" *-- "many"  Digit
package "Main" #DDDDDD {
  class Animation
  class Main
  class info_page1
  class info_page2
  class ChooseLevel
  class ChooseWhichHighScorePage
  class SceneController
  Main "1" *-- "1" SceneController
  Main "1" *-- "1" info_page1
  Main "1" *-- "1" info_page2
  Main "1" *-- "1" ChooseLevel
  Main "1" *-- "1" ChooseWhichHighScorePage
}
package "Game High Score" #DDDDDD {
  class HighscoreManager
  class Score
  interface GetHighScoreScene
  class highScorePage
  GetHighScoreScene <|-- highScorePage
  highScorePage "1" *-- "1"  HighscoreManager
  highScorePage "1" *-- "many" Score
  HighscoreManager "1" *-- "many" Score
}
Main "1" *-- "many" GetHighScoreScene
package "Game Levels" #DDDDDD {
  interface GameScene
  class gameLv1
  class gameLv2
  class gameLv3
  GameScene <|-- gameLv1
  GameScene <|-- gameLv2
  GameScene <|-- gameLv3
}
Main "1" *-- "many" GameScene



Main <|- Animation









@enduml